### ISSUE TITLE
Add Github Workflow test fail/success running badge

### ISSUE THREAD

**Issue by mgroves** [mgroves/NoSqlMigrator#15]
Add to readme

**Comment by chillerno1** [comment]
Hi @mgroves, I'm happy to pick this up and submit a PR if you'd like help with this. Is it the [CI for NoSqlMigrator](https://github.com/mgroves/NoSqlMigrator/actions/runs/5501280965) action you want to add a badge for?

**Comment by mgroves** [comment]
Excellent, thank you very much!
